# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05286f1a1eb8ca2b921682c9188d27c6f45540dd61c036aee2c9994ec622ed6b43d4324bc2a7438437355bce5cfe3ca98f5b594b573af4b0cbb9caa25c79552a

test:
  secret_key_base: cfc592fb0ad41b68bb225ece28edd0873839f88499a05c633e462e6a08caaa136d2f58dc9b09902308860130ebde97beb4f606fa0c794c6329b26d5b81bc4dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
